name: wsi_break_time
description: "Wsi Break Time - Proteção para seus olhos (Android)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^18.0.1
  uuid: ^4.5.1
  provider: ^6.1.2
  wakelock_plus: ^1.2.8
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
